### ISSUE TITLE
Clarify where fluid viewhelpers should be documented / Provide overview of what to find where. 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#100]
Clarify where fluid viewhelpers should be documented. There was a discussion in the `#typo3-cms channel `on slack. There seem to be several things that are confusing for users, see : https://typo3.slack.com/archives/C025BQLFA/p1519219789000101

- Documentation  https://fluidtypo3.org/viewhelpers/fluid/master.html is not up to date
-  This documentation (https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Index.html) : ?

**Comment by taalas** [comment]
I would also like to add that it could be benificial to document the different versioning schemes and/or flavors of Fluid:

- typo3fluid/fluid
- typo3/cms-fluid
- typo3/fluid (just for clarification)

**Comment by sypets** [comment]
Thanks for your input. I find that important too. But I would suggest you create a new issue for that. This issue is for **fluid viewhelpers**. It will make browsing / searching through issues easier if we provide 1 issue for one specific topic. Thanks.

**Comment by taalas** [comment]
@sypets agreed

**Comment by tmotyl** [comment]
Core view helper documentation should be auto generated from the viewhelper source files.
This reference should replace the one from this guide.

We can use the same tool Claus uses to run his fluidtypo3.org website.
There is a schemamaker https://github.com/FluidTYPO3/schemaker which has two modes. For the FE renderings it will consume XSD files - for the optional BE you can render installed ViewHelper namespaces based on live classes.

So in first step we need to generate XSD schema. And then generate html out of the schema.

These days Claus is working on a static site generate that eats XSD and poops out HTML and JSON references so it can also be used by remotes to read out docs of a specific package, VH, vendor, whatever.

We can use the tool once it's published. Or if we decide to start working on the topic right now, we can use  simplexml to load the document, xpath to iterate all elements, xpath to extract each element's values and docs - and pipe the doc comment through RST or whatever you need.

**Comment by sypets** [comment]
As VH Ref generation is a general issue, I am closing this in favor of the general one in the T3Docs Team repo: https://github.com/TYPO3-Documentation/T3DocTeam/issues/16

**Comment by sypets** [comment]
Correction: close in favor of https://github.com/TYPO3-Documentation/T3DocTeam/issues/9

sorry.
