### ISSUE TITLE
Added absolute url option to uri.image and image viewHelper

### ISSUE THREAD

**Issue by r4fx** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#115]
As changes says: 
https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.6/Feature-64286-AddedAbsoluteUrlOptionToUriimageAndImageViewHelper.html

this should be target to https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Image.html
and
https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Image.html

**Comment by sypets** [comment]
@npostnik Please keep in mind that long term, the manual ViewHelper references here will be replaced by the automatically generated ones. The versions for 8.7 and 6.2 will still be maintained here for a while.

For the change you propose. You are welcome to make changes yourself:

1. load the page in the browser
2. "Edit me on GitHub"
3. proceed ...

More information: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html
