### ISSUE TITLE
Update documentation on f:comment, add f:format.cdata

### ISSUE THREAD

**Issue by npostnik** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#130]
In the documentation to f:comment there is an example with CDATA. It says that content wrapped in CDATA will be displayed but not processed. This is not true in TYPO3 version 8. Wrapping a block in CDATA has the same effect as f:comment.

There is a new viewhelper f:format.cdata, content will be wrapped in CDATA on output.

**Comment by sypets** [comment]
@npostnik Please keep in mind that long term, the manual ViewHelper references here will be replaced by the automatically generated ones. The versions for 8.7 and 6.2 will still be maintained here for a while.

For the change you propose. You are welcome to make changes yourself:

1. load the page in the browser
2. "Edit me on GitHub"
3. proceed ...

More information: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html
