### ISSUE TITLE
Status of this manual?!

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#143]
After talking with Lolli:

1. Move remaining things (not much left) to appropriate other manuals (probably Extbase / Fluid book or "TYPO3 Explained"). 
2. The ViewHelper reference for 8.7 and 6.2 should still be kept
3. Take down this manual.

See: https://docs.typo3.org/Home/About/News/2019/Index.html#news-2019-06-26

Todos:

* [ ] Check with SkillsDisplay for existing links to Extbase / Fluid guide
* [ ] check inlinks / piwik / search queries etc. for pages that may still be relevant
* [ ] move relevant parts to "TYPO3 Explained"
* [ ] check with participants from Fluid sprint for start page for Fluid
* [x] announce deprecation in Slack channel
* [x] explain deprecation as Changelog on docs.typo3.org: https://docs.typo3.org/Home/About/News/2019/Index.html#news-2019-06-26

**Comment by linawolf** [comment]
The Guide was archived
