### ISSUE TITLE
Wrong description concerning placeholder in f:form.textfield

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#28]
https://forge.typo3.org/issues/76061

On https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Form/Textfield.html the function of the placeholder is described in German with:

> Ein beliebiger Text, der verschwindet, sobald in dieses Feld reingeklickt wird.

This information is wrong. Right is:

> Ein beliebiger Text, der verschwindet, sobald Etwas in dieses Feld eingetragen wird.

**Comment by marble** [comment]
Solved.
