### ISSUE TITLE
f:switch suggest using partials wich is wrong

### ISSUE THREAD

**Issue by guppy42** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#45]
This section;
> The use of this ViewHelper is often a sign of a weak programming architecture. If the f:switch ViewHelper is used a lot, then a better approach would be to re-consider the architecture within the Actions and the Controller.

>Tip
>The example above could alternatively be solved by using a Partial or Section for each gender, although performance issues need to be considered. (See f:render.)

><f:render partial="person/{person.gender}" />

Is not only oddly biased but also wrong,  if person.gender were eg. 7 it would fail horribly crashing the frontend rendering due to a missing partial.

I suggest the text be altered to

>Tip
> If in the example above all possible values are well defined it could alternatively be solved by using a Partial or Section for each defined value, although performance issues need to be considered. (See f:render.)
><f:render partial="person/{person.gender}" />

removing the bit about "weak programming architecture"

**Comment by sypets** [comment]
Thank you for the issue. Sorry about the late reply. 

Could you add a link to the section you are talking about next time? It would make it easier to check your suggestions and make the change. 

You might also consider to make changes yourself (create a Pull Request). Please see the official documentation about how to do this:   https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html
