### ISSUE TITLE
extending an extbase example doesn't work

### ISSUE THREAD

**Issue by scibile** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#47]
typo3 v7.6.14 - I build the product overview and up to the last step very helpfull. Changing the category selection from inline to select works grafically but the selections do not store ...

I tried for days now but have found no solution, i noticed the selection for the relation of the tables (IRRE or ... don't recalll) in extension-builder which might be a new option since not mentioned in the tutorial, but also that selection gives the same result in both cases.

**Comment by marble** [comment]
Hello Gert-jan, I'm feeling with you as I know the situation: You're seriously trying and it simply doesn't work. And, yes, you're absolutely right: Asking is what you need to do. The only problem is: Not many people will be reading here. So I'd like to encourage you to get instant access to the TYPO3 communication platform https://typo3.slack.com To do so go to https://forger.typo3.org/slack 
Once you're logged in to Slack go to the #cig-extbase channel and ask again. Keep on: there'll be an answer to your question!

**Comment by scibile** [comment]
thank you, I did report here because I'm also a team-worker, its not acceptable that a basic tutorial does not give all details to make the example work !! I'm sure it has to do with outdated info, I saw that the TCA was still created as Product.php, in my extension builder that is tx_productoverview_domain_model_product.php, further does the builder give options not discussed ...

thx by the way for your work, contributor !! I'm still only a very willing ear

**Comment by sypets** [comment]
I am closing this due to #143
