### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#61]
In https://docs.typo3.org/typo3cms/ExtbaseGuide/Extbase/Step3Documentation/Architecture.html
it's mentioned about "TYPO3 FLOW" and might be confusing. I propose to exchange it by "extbase".

The long text with all the modules in my opinion would be better written as list either numbered or just with points, but as text it's not designed for easy reading. If it's changed to list-view then I propose further to restructure the text a bit, that the list is sorted in the bottom of all other text.

**Comment by DavidBruchmann** [comment]
As there is no chapter about each extbase-module I propose to mention at least the corresponding classes for each. With this additional info the list could become a table, but at least the different modules would be optical separated.

**Comment by sypets** [comment]
I am closing this due to #143
