### ISSUE TITLE
Dispatcher

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#62]
The site https://docs.typo3.org/typo3cms/ExtbaseGuide/Extbase/Step3Documentation/Dispatcher.html
is using outdated naming-schemes and classes.

Examples:
- Tx_Extbase_MVC_Web_FrontendRequestHandler
- t3lib_div::getIndpEnv('TYPO3_SITE_URL')

**Comment by DavidBruchmann** [comment]
same for Controller:
https://docs.typo3.org/typo3cms/ExtbaseGuide/Extbase/Step3Documentation/ActionController.html

**Comment by sypets** [comment]
I am closing this due to #143
