### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by hg2000** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#79]
On Page: 
https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Translate.html

there is a missing quote in:
<f:translate key="LLL:fileadmin/lang/locallang.xml:domain_model.bestfilm" arguments="{0: 'Back to the Future, 1: '1985'}" />

correct:
<f:translate key="LLL:fileadmin/lang/locallang.xml:domain_model.bestfilm" arguments="{0: 'Back to the Future', 1: '1985'}" />

**Comment by marble** [comment]
Hi, you're welcome. How about doing it yourself? Clicking "Edit me on Github", change it, and send a Pull request. That's the best procedure. Just try it!

**Comment by marble** [comment]
I've fixed it. Don't hesitate to send a pull request next time.
