### ISSUE TITLE
Idea: Add link to API

### ISSUE THREAD

**Issue by ursbraem** [TYPO3-Documentation/TYPO3CMS-Guide-Extbase#84]
For a "handwritten" documentation, it can be difficult to keep track with the code.
What about adding a link to the API or even the class?

So for example on https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Image.html

either
https://api.typo3.org/typo3cms/8/html/class_t_y_p_o3_1_1_c_m_s_1_1_fluid_1_1_view_helpers_1_1_uri_1_1_image_view_helper.html

or even better
https://api.typo3.org/typo3cms/8/html/fluid_2_classes_2_view_helpers_2_uri_2_image_view_helper_8php_source.html

?

**Comment by marble** [comment]
Yes, sure, why not? OTH, what I've learned: We actually have the possibility to create symbolic (!) deep links into the phpdocs with the Sphinx crossreferencing mechanism "Intersphinx". When that became possible we joyfully started using that. On the other hand it became visible very soon the the phpdocs changed very much, as we didn't catch up with linking to the right version. So, my advice would be: Add some kind of general link that probably will stay valid.

**Comment by ursbraem** [comment]
Maybe just a link to https://api.typo3.org/typo3cms/8/html/index.html 

For distracted people like me, maybe a tutorial like this?

Often, the source code of a ViewHelper can be helpful and provide further insight. 
Here's an example on how to access the source for a ViewHelper:

* Visit https://api.typo3.org/typo3cms/8/html/index.html 
* All Viewhelper classes follow the same naming convention.  If you want information about `<f:uri.image>`, type "imageviewhelper" into the search box. You will receive a list of Image ViewHelpers.

![image](https://user-images.githubusercontent.com/1446443/33474655-dc4c6004-d67b-11e7-8287-68ce60552035.png)

Choose the one with the right namespace. In this case, `TYPO3::CMS::Fluid::ViewHelpers::Uri`

* On the following page, look for the path to the PHP class:

![image](https://user-images.githubusercontent.com/1446443/33474712-0b2e1494-d67c-11e7-8c91-0094073cfccf.png)

[Here you go](https://api.typo3.org/typo3cms/8/html/fluid_2_classes_2_view_helpers_2_uri_2_image_view_helper_8php_source.html) – in this example, you will see that a ViewHelper is quite transparent to read and check the arguments it accepts.

**Comment by marble** [comment]
Can you prepare a pull request?

**Comment by ursbraem** [comment]
Is it possible to reuse content on each pages, like add a link to said text on each page?

**Comment by marble** [comment]
?
Maybe one real PR would help to see what you exactly mean.

**Comment by ursbraem** [comment]
ok 😀

**Comment by sypets** [comment]
While I think this is a good idea, it is currently not to be recommended. 

It is planned to shutdown **api.typo3.org**, see https://decisions.typo3.org/t/shut-down-api-typo3-org/355

What you could do is add links to the TYPO3 source on Github. I am not sure if this is a good idea though, because it will be tedious to maintain these links correctly. No links is IMHO opinion better than incorrect or broken links. 

If this is still important to you, please consider raising the topic in #typo3-documentation on Slack (see https://typo3.org/help).  or creating a pull request (see https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html)

**Comment by ursbraem** [comment]
Thanks Sibylle – I had a bad conscience anyway because I proposed something and then didn't go on.
